services:
  - type: web
    name: leetlab-backend
    env: node
    rootDir: packages/backend
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 8081
      - key: DATABASE_URL
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: CLIENT_URL
        sync: false
      - key: JUDGE0_API_URL
        value: https://judge0-ce.p.rapidapi.com
      - key: JUDGE0_API_KEY
        sync: false
